env:
  PLATFORM: linux/amd64,linux/riscv64

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
"on":
  pull_request:
    branches:
      - ci
  workflow_dispatch:
    inputs:
      stagex_git_ref:
        description: StageX git ref to checkout (branch, tag, sha). Leave empty to use the STAGEX_REF pinned in the Makefile.
        type: ""
        required: false
name: default
jobs:
  default:
    permissions:
      actions: read
      contents: write
      issues: read
      packages: write
      pull-requests: read
      id-token: write
    runs-on:
      - ubuntu-latest
    if: (!startsWith(github.head_ref, 'renovate/') && !startsWith(github.head_ref, 'dependabot/'))
    timeout-minutes: 720
    steps:
      - name: gather-system-info
        id: system-info
        uses: kenchan0130/actions-system-info@59699597e84e80085a750998045983daa49274c4 # version: v1.4.0
        continue-on-error: true
      - name: print-system-info
        run: |
          MEMORY_GB=$((${{ steps.system-info.outputs.totalmem }}/1024/1024/1024))

          OUTPUTS=(
            "CPU Core: ${{ steps.system-info.outputs.cpu-core }}"
            "CPU Model: ${{ steps.system-info.outputs.cpu-model }}"
            "Hostname: ${{ steps.system-info.outputs.hostname }}"
            "NodeName: ${NODE_NAME}"
            "Kernel release: ${{ steps.system-info.outputs.kernel-release }}"
            "Kernel version: ${{ steps.system-info.outputs.kernel-version }}"
            "Name: ${{ steps.system-info.outputs.name }}"
            "Platform: ${{ steps.system-info.outputs.platform }}"
            "Release: ${{ steps.system-info.outputs.release }}"
            "Total memory: ${MEMORY_GB} GB"
          )

          for OUTPUT in "${OUTPUTS[@]}";do
            echo "${OUTPUT}"
          done
        continue-on-error: true
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # version: v6.0.2
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Set up Namespace CLI
        uses: namespacelabs/nscloud-setup@v0
      - name: Set up amd64 cross-compile builder
        uses: namespacelabs/nscloud-setup-buildx-action@v0
        with:
          builder-name: stagex-amd64
      - name: Set up Docker Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0
      - name: Set up riscv64 builder
        run: |
          mkdir -p _out
          echo "$BUILDER_NODE_0_AUTH_TLS_CACERT" > _out/ca.pem
          echo "$BUILDER_NODE_0_AUTH_TLS_CERT" > _out/cert.pem
          echo "$BUILDER_NODE_0_AUTH_TLS_KEY" > _out/key.pem
          docker buildx create --append --name nsc-remote --driver remote --platform linux/riscv64 tcp://buildkit-riscv64.tplant.com.au:1234 \
          --driver-opt cacert=${PWD}/_out/ca.pem,cert=${PWD}/_out/cert.pem,key=${PWD}/_out/key.pem
        env:
          BUILDER_NODE_0_AUTH_TLS_CACERT: ${{ secrets.BUILDKIT_RISCV64_CACERT }}
          BUILDER_NODE_0_AUTH_TLS_CERT: ${{ secrets.BUILDKIT_RISCV64_CERT }}
          BUILDER_NODE_0_AUTH_TLS_KEY: ${{ secrets.BUILDKIT_RISCV64_KEY }}
      - name: Clone stagex
        env:
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make clone
      - name: Patch stagex
        run: |
          make patch
      - name: login-to-registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # version: v4.2.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - name: Set up crane
        run: |
          curl -sL "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz" > go-containerregistry.tar.gz
          tar -zxvf go-containerregistry.tar.gz -C /usr/local/bin/ crane
      - name: Seed fetch cache
        env:
          FETCH_CACHE_IMAGE: ghcr.io/${{ github.repository_owner }}/stagex/fetch-cache:staging
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make fetch-seed
      - name: stage0
        env:
          CROSS_BUILDER_NAME: stagex-amd64
          PROGRESS: plain
          REGISTRY_USERNAME: ${{ github.event_name != 'pull_request' && 'ghcr.io' || 'registry.dev.siderolabs.io' }}/${{ github.repository_owner }}/stagex
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make stage0
      - name: stage1
        env:
          CROSS_BUILDER_NAME: stagex-amd64
          PROGRESS: plain
          REGISTRY_USERNAME: ${{ github.event_name != 'pull_request' && 'ghcr.io' || 'registry.dev.siderolabs.io' }}/${{ github.repository_owner }}/stagex
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make stage1
      - name: stage2
        env:
          CROSS_BUILDER_NAME: stagex-amd64
          PROGRESS: plain
          REGISTRY_USERNAME: ${{ github.event_name != 'pull_request' && 'ghcr.io' || 'registry.dev.siderolabs.io' }}/${{ github.repository_owner }}/stagex
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make stage2
      - name: stage3
        env:
          CROSS_BUILDER_NAME: stagex-amd64
          PROGRESS: plain
          REGISTRY_USERNAME: ${{ github.event_name != 'pull_request' && 'ghcr.io' || 'registry.dev.siderolabs.io' }}/${{ github.repository_owner }}/stagex
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make stage3
      - name: core
        env:
          CROSS_BUILDER_NAME: stagex-amd64
          PROGRESS: plain
          REGISTRY_USERNAME: ${{ github.event_name != 'pull_request' && 'ghcr.io' || 'registry.dev.siderolabs.io' }}/${{ github.repository_owner }}/stagex
          STAGEX_REF: ${{ inputs.stagex_git_ref }}
        run: |
          make core
